// farm-byte-ui/src/app/layout/sidebar/sidebar-menu/sidebar-menu.component.ts
import {Component, inject, input, InputSignal, OnInit} from '@angular/core';
import {NavbarMenuStore} from "../../store/navbar-menu.store";
import {SidebarMenu} from "../../models/sidebar-menu.model";
import {SidebarMenuStore} from "../../store/sidebar-menu.store";
import {Router} from "@angular/router";
import {NavbarMenu} from "../../models/navbar-menu.model";
import {NgClass} from "@angular/common";
import {TranslateModule} from "@ngx-translate/core";

@Component({
  selector: 'farmbyte-sidebar-menu',
  standalone: true,
  imports: [
    NgClass,
    TranslateModule
  ],
  templateUrl: './sidebar-menu.component.html',
  styleUrl: './sidebar-menu.component.scss'
})
export class SidebarMenuComponent implements OnInit{
  sidebarMenu: InputSignal<SidebarMenu> = input.required();
  readonly navbarMenuStore = inject(NavbarMenuStore);
  readonly sidebarMenuStore = inject(SidebarMenuStore);
  readonly router = inject(Router);

  ngOnInit(): void {
    this.initSidebar();
  }

  private initSidebar() {
    if (this.sidebarMenuStore.sidebarMenus()) {
      this.navbarMenuStore.loadNavbarMenus(
        this.sidebarMenuStore.sidebarMenus()[1]?.navbarMenuItems as NavbarMenu[],
        this.sidebarMenuStore.sidebarMenus()[1]?.label
      );
      this.sidebarMenuStore.updateCurrentSidebarMenu(this.sidebarMenuStore.sidebarMenus()[0] as SidebarMenu);
    }
  }

  onClick(sidebarMenu: SidebarMenu | undefined): void {
    this.navbarMenuStore.loadNavbarMenus(
      sidebarMenu?.navbarMenuItems? sidebarMenu.navbarMenuItems: [],
      sidebarMenu?.label? sidebarMenu.label: ''
    );
    this.sidebarMenuStore.updateCurrentSidebarMenu(sidebarMenu as SidebarMenu);
    this.router.navigate([sidebarMenu?.link]).then(() => {});
  }
}

<a (click)="onClick(sidebarMenu())"
   [ngClass]="sidebarMenu().label === sidebarMenuStore.selectedSidebarMenu()?.label? 'border-round-2xl bg-purple-900 opacity-70': ''"
   class="flex flex-row justify-content-start align-items-center text-white gap-2 p-3 border-round-2xl w-full  cursor-pointer hover:bg-purple-900 hover:bg-opacity-20 hover:border-round-2xl">
  <span class="material-symbols-outlined">{{sidebarMenu().icon || ''}}</span>
  <span class="sm:hidden md:block">{{sidebarMenu().label || '' | translate}}</span>
</a>

// farm-byte-fronend/src/layouts/sidebar/SidebarMenu.tsx
import React from "react";
import {useDispatch, useSelector} from "react-redux";
import {useNavigate} from "react-router-dom";
import {useTranslation} from "react-i18next";

import {SidebarMenuModel} from "@/layouts/model/sidebar-menu.ts";
import {RootDispatch, RootState} from "@/store/store.ts";
import {selectSidebarMenu} from "@/layouts/state/sidebar-menu-slice.ts";
import {updateNavbarMenus} from "@/layouts/state/navbar-menu-slice.ts";

type Props = {
    sidebarMenu: SidebarMenuModel,
    isOpen: boolean,
}

const SidebarMenu = ({sidebarMenu, isOpen}: Props) => {
    const {t} = useTranslation(['home']);
    const dispatch = useDispatch<RootDispatch>();
    const selectedSidebarMenu = useSelector((state: RootState) => state.sidebar.selectedSidebarMenu);
    const navigate = useNavigate();

    const handleSelectSidebarMenu = (_event: React.MouseEvent<HTMLDivElement>, sidebarMenu: SidebarMenuModel) => {
        _event.preventDefault();
        dispatch(selectSidebarMenu(sidebarMenu));
        if(sidebarMenu.navbarMenu) {
            dispatch(updateNavbarMenus(sidebarMenu.navbarMenu));
        } else {
            dispatch(updateNavbarMenus([]));
        }
        navigate(sidebarMenu.link);
    }

    return (
        <div onClick={(event) => handleSelectSidebarMenu(event, sidebarMenu)}
              className={`flex flex-row ${isOpen ? 'justify-start' : 'justify-center'} ${selectedSidebarMenu?.link === sidebarMenu.link? 'bg-amber-900/40 text-amber-500': ''} items-center gap-3 px-3 py-5 cursor-pointer w-full text-white hover:bg-amber-900/40 hover:text-amber-500 hover:transition hover:duration-300 hover:ease-in-out`}>
            <span className="material-symbols-outlined">{sidebarMenu.icon}</span>
            <p className={`${isOpen ? 'transition-all ease-out duration-300 opacity-100' : 'hidden transition-all ease-in duration-300 opacity-0'}`}>{t(sidebarMenu.label)}</p>
        </div>
    );
}


export default SidebarMenu;
