// farm-byte-fronend/src/layouts/navbar/navbar-menu/NavBarProfile.tsx
import React, {useRef, useState} from "react";
import {useNavigate} from "react-router-dom";

const NavBarProfile = () => {

    const dropdownRef = useRef<HTMLDivElement>(null);
    const [isOpenProfileMenu, setIsOpenProfileMenu] = useState(false);
    const navigate = useNavigate();

    const toggleDropDown = () => {
        setIsOpenProfileMenu(!isOpenProfileMenu);
    }

    const handleNavigateTo = (event: React.MouseEvent<HTMLDivElement>, link: string) => {
        event.preventDefault();
        navigate(link);

    }

    return (
        <div className="relative cursor-pointer">
            <div
                ref={dropdownRef}
                onClick={toggleDropDown}
                className="flex flex-row justify-start items-center text-gray-500 hover:text-amber-700">
                <span className="font-medium">
                    <img src="/images/profile.png" alt="..." className="size-8 object-cover rounded-full"/>
                </span>

            </div>
            <div
                className={`absolute top-full -right-0 mt-3.5 w-32 bg-white shadow-2xl z-10 ${isOpenProfileMenu ? 'transition duration-300 ease-in opacity-100 transform scale-110' : 'transition duration-300 ease-out opacity-0 scale-75'}`}>
                <div onClick={(event) => handleNavigateTo(event,'/user/profile')}
                      className="block text-gray-500 p-2 text-sm hover:text-white hover:bg-amber-700 hover:transition-all hover:ease-in-out hover:duration-300 ">My profile</div>
                <div onClick={(event) => handleNavigateTo(event, '/logout')}
                      className="block text-gray-500 p-2 text-sm hover:text-white hover:bg-amber-700 hover:transition-all hover:ease-in-out hover:duration-300 ">Logout</div>
            </div>
        </div>
    );
}

export default NavBarProfile;

// farm-byte-ui/src/app/layout/navbar/navbar-profile/navbar-profile.component.ts
import {Component, HostListener, signal, WritableSignal} from '@angular/core';
import {NgClass} from "@angular/common";

@Component({
  selector: 'farmbyte-navbar-profile',
  standalone: true,
  imports: [
    NgClass
  ],
  templateUrl: './navbar-profile.component.html',
  styleUrl: './navbar-profile.component.scss'
})
export class NavbarProfileComponent {

  isOpen: WritableSignal<boolean> = signal(false);

  toggleDropDown() {
    this.isOpen.set(!this.isOpen());
  }

  @HostListener('document:click', ['$event'])
  onClickOutside(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const clickInside = target.closest('#dropDownMenuItem_profile');
    if (!clickInside) {
      this.isOpen.set(false);
    }
  }
}

<a id="dropDownMenuItem_profile" (click)="toggleDropDown()" class="relative flex text-gray-700 py-1 px-2 cursor-pointer" >
  <div class="flex flex-row justify-content-center align-items-center gap-1">
    <span class="hover:text-purple-500">
      <img class="size-1.5rem object-cover border-circle" src="./assets/images/profile.png" alt="profile">
    </span>
  </div>
  @if(isOpen()) {
    <div
      [ngClass]="isOpen()? 'transition ease-out duration-1000 transform opacity-100 scale-100' : 'transition ease-in duration-1000 transform opacity-0 scale-10'"
      class="absolute right-0 mt-2.7rem w-8rem border-top-2 border-purple-500  bg-white  border-round-bottom-xl shadow-6 z-3">

      <a class="flex flex-row justify-start items-center text-sm p-2 gap-2 hover:transition hover:duration-300 hover:bg-gray-200 hover:text-black">
        <span>My Profile</span>
      </a>
      <a class="flex flex-row justify-start items-center text-sm p-2 gap-2 border-round-bottom-xl hover:transition hover:duration-300 hover:bg-gray-300 hover:text-black">
        <span>Logout</span>
      </a>

    </div>
  }
</a>
