// farm-byte-fronend/src/layouts/Layout.tsx
import Sidebar from "@/layouts/sidebar/Sidebar.tsx";
import WebNavbar from "@/layouts/navbar/WebNavbar.tsx";
import MobileNavbar from "@/layouts/navbar/MobileNavbar.tsx";
import {Outlet} from "react-router-dom";

const Layout = () => {
    return (
        <div className="flex flex-row min-h-screen bg-neutral-50">
            <div className="hidden md:block">
                <div className="flex flex-row w-screen">
                    <Sidebar/>
                    <div className="flex flex-col w-full">
                        <WebNavbar/>
                        <div className="container grow mx-auto my-8 flex-1 py-10">
                            <Outlet/>
                        </div>
                    </div>
                </div>
            </div>
            <div className="md:hidden">
                <MobileNavbar/>
                <div className="container mx-auto flex-1 py-10">
                    <Outlet/>
                </div>
            </div>
        </div>
    );
}

export default Layout;

// farm-byte-portal/src/app/layout/layout.component.ts
import {Component} from '@angular/core';
import {NavbarComponent} from "./navbar/navbar.component";
import {SidebarComponent} from "./sidebar/sidebar.component";
import {RouterOutlet} from "@angular/router";

@Component({
  selector: 'farmbyte-layout',
  standalone: true,
  imports: [
    NavbarComponent,
    SidebarComponent,
    RouterOutlet
  ],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.scss'
})
export class LayoutComponent {
}

<div class="flex flex-col w-screen h-screen">
  <farmbyte-navbar  />
  <div class="flex flex-row">
    <farmbyte-sidebar/>
    <div class="w-full">
      <router-outlet/>
    </div>
  </div>
</div>
