// farm-byte-ui/src/layouts/Layout.tsx
import Sidebar from "@/layouts/sidebar/Sidebar.tsx";
import WebNavbar from "@/layouts/navbar/web-navbar/WebNavbar.tsx";
import MobileNavbar from "@/layouts/navbar/mobile-navbar/MobileNavbar.tsx";
import {Outlet} from "react-router-dom";
import {useSelector} from "react-redux";
import {selectIsOpenSidebarMenu} from "@/layouts/sidebar/SidebarMenuSlice.ts";



const Layout = () => {
    const isOpen: boolean = useSelector(selectIsOpenSidebarMenu);
    return (
        <div className="flex flex-row min-h-screen overflow-x-hidden">
            <div className="hidden md:block">
                <div className="flex flex-row w-screen">
                    <div className="hidden md:block">
                        <Sidebar/>
                    </div>
                    <div className="flex flex-col w-full">
                        <div className="hidden md:block fixed w-full z-10">
                            <WebNavbar/>
                        </div>
                        <div className="md:hidden">
                            <MobileNavbar/>
                        </div>
                        <div
                            className={`min-h-full flex-1 mt-32 ${isOpen ? 'ml-72 transition-all ease-linear duration-300' : 'ml-24 transition-all ease-linear duration-300'}`}>
                            <Outlet/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default Layout;

// farm-byte-portal/src/app/layout/layout.component.ts
import {Component, inject} from '@angular/core';
import {SidebarComponent} from "./sidebar/sidebar.component";
import {NavbarComponent} from "./navbar/navbar.component";
import {RouterOutlet} from "@angular/router";
import {NavBarStore} from "./navbar/navbar.store";
import {NgClass} from "@angular/common";

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [
    SidebarComponent,
    NavbarComponent,
    RouterOutlet,
    NgClass
  ],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.scss'
})
export class LayoutComponent {
  readonly navbarStore = inject(NavBarStore);
}

<div class="h-screen w-screen flex flex-row">
  <div
    [ngClass]="navbarStore.toggleSidebar()? 'md:w-[70px] transition-all ease-in duration-300': 'md:w-[250px] transition-all ease-in duration-300'"
    class="md:w-[250px] xm:w-[70px] bg-amber-900 h-full">
    <app-sidebar/>
  </div>
  <div class="md:w-full xm:w-full">
    <div class="flex flex-col bg-gray-50">
      <app-navbar/>
      <div class="p-8">
        <router-outlet/>
      </div>
    </div>
  </div>
</div>
