// farm-byte-ui/src/layouts/navbar/web-navbar/NavBarLanguage.tsx
import React, {useEffect, useRef, useState} from "react";
import {LanguageModel} from "@/layouts/model/LanguageModel.ts";
import {useDispatch, useSelector} from "react-redux";
import {useTranslation} from "react-i18next";
import {changeLanguage, selectLanguage} from "@/layouts/navbar/NavbarMenuSlice.ts";
import {RootDispatch} from "@/Store.ts";
import {getImageUrl} from "@/utils/imageUtils.ts";

const NavBarLanguage = () => {

    const {i18n} = useTranslation(['home']);

    const dispatch = useDispatch<RootDispatch>();
    const language: LanguageModel = useSelector(selectLanguage);

    const dropdownRef = useRef<HTMLDivElement>(null);
    const [isOpenLanguageMenu, setIsOpenLanguageMenu] = useState(false);

    useEffect(() => {
        // @ts-expect-error
        const closeDropDown = (event) => {
            if(dropdownRef.current && !dropdownRef.current.contains(event.target)) {
                setIsOpenLanguageMenu(false);
            }
        }
        document.addEventListener("click", closeDropDown);
        return () => document.body.removeEventListener("click", closeDropDown);
    }, []);

    const toggleDropDown = () => {
        setIsOpenLanguageMenu(!isOpenLanguageMenu);
    }

    const handleChangeLanguage = (event: React.MouseEvent<HTMLDivElement>, language: LanguageModel) => {
        //TODO continue to find how to hide sub menu
        event.preventDefault();
       if(isOpenLanguageMenu) {
           i18n.changeLanguage(language.name).then();
           dispatch(changeLanguage(language));
       }
    }

    return (
        <div className="relative mr-5">
            <div
                ref={dropdownRef}
                onClick={toggleDropDown}
                className="flex flex-row justify-start items-center text-secondary-500 hover:text-primary cursor-pointer">
                    <span className="font-medium">
                        <img src={`${language.name === 'fr' ? getImageUrl('/images/french.png') : getImageUrl('/images/english.png')}`} alt="..."
                             className="size-6 object-cover rounded-full"/>
                    </span>
            </div>
            <div
                className={`absolute top-full -right-0 mt-8 w-32 bg-white shadow-2xl z-10 rounded-b-lg ${isOpenLanguageMenu ? 'transition-all duration-300 ease-in opacity-100 transform scale-110 cursor-pointer' : 'cursor-auto transition-all duration-300 ease-out opacity-0 scale-75'}`}>
                <div onClick={(event) => handleChangeLanguage(event, {name: 'en'})}
                     className="flex flex-row justify-start items-center gap-2 text-secondary-500 p-2 text-sm hover:text-primary-foreground hover:bg-gradient-to-r hover:from-primary hover:to-primary hover:transition-all hover:ease-in-out hover:duration-300 ">
                    <img src={getImageUrl('/images/english.png')} alt="..." className="size-6 object-cover rounded-full"/>
                    <span>English</span>
                </div>
                <div onClick={(event) => handleChangeLanguage(event, {name: 'fr'})}
                     className="flex flex-row justify-start items-center gap-2 text-secondary-500 p-2 text-sm  rounded-b-lg hover:text-primary-foreground hover:bg-gradient-to-r hover:from-primary hover:to-primary hover:transition-all hover:ease-in-out hover:duration-300">
                    <img src={getImageUrl('/images/french.png')} alt="..." className="size-6 object-cover rounded-full"/>
                    French
                </div>
            </div>
        </div>
    );
}

export default NavBarLanguage;

// farm-byte-portal/src/app/layout/navbar/navbar-language/navbar-language.component.ts
import {Component, HostListener, inject, OnInit, signal, WritableSignal} from '@angular/core';
import {RouterLink} from "@angular/router";
import {TranslateModule, TranslateService} from "@ngx-translate/core";
import {NgClass} from "@angular/common";
import {Language, NavbarMenuStore} from "../../navbar-menu.store";

@Component({
  selector: 'farmbyte-navbar-language',
  standalone: true,
  imports: [
    RouterLink,
    TranslateModule,
    NgClass
  ],
  templateUrl: './navbar-language.component.html',
  styleUrl: './navbar-language.component.scss'
})
export class NavbarLanguageComponent implements OnInit {

  isOpen: WritableSignal<boolean> = signal(false);
  readonly navbarMenuStore = inject(NavbarMenuStore);
  readonly translate = inject(TranslateService);

  toggleDropDown(): void {
    this.isOpen.set(!this.isOpen());
  }

  @HostListener('document:click', ['$event'])
  onClickOutside(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const clickInside = target.closest('#dropDownMenuItem_language');
    if (!clickInside) {
      this.isOpen.set(false);
    }
  }

  selectLanguage(language: Language) {
    this.navbarMenuStore.changeLanguage(language);
  }

  ngOnInit(): void {
    this.translate.use(this.navbarMenuStore.selectedLanguage());
  }
}

<a id="dropDownMenuItem_language" (click)="toggleDropDown()" class="relative flex text-gray-500 py-1 px-2 cursor-pointer" >
  <div class="flex flex-row justify-center items-center gap-1">
    <span>
      <img class="size-6 object-cover rounded-full" src="./images/{{navbarMenuStore.selectedLanguage() == 'en'? 'english': 'french'}}.png" alt="french">
    </span>
  </div>
  @if(isOpen()) {
    <div
      [ngClass]="isOpen()? 'transition ease-out duration-1000 transform opacity-100 scale-100' : 'transition ease-in duration-1000 transform opacity-0 scale-10'"
      class="absolute top-full right-0 mt-2 w-32 border-2 border-t-orange-700  bg-white shadow-lg z-10">

        <a (click)="selectLanguage('fr')" class="block flex flex-row justify-start items-center text-sm p-2 gap-2 hover:transition hover:duration-300 hover:bg-gray-200 hover:text-black">
          <img class="size-6 object-cover rounded-full" src="./images/french.png" alt="french">
          <span>{{ 'navbarMenu_language_fr' | translate}}</span>
        </a>
        <a (click)="selectLanguage('en')" class="block flex flex-row justify-start items-center text-sm p-2 gap-2 hover:transition hover:duration-300 hover:bg-gray-300 hover:text-black">
          <img class="size-6 object-cover rounded-full" src="./images/english.png" alt="english">
          <span>{{ 'navbarMenu_language_en' | translate}}</span>
        </a>

    </div>
  }
</a>
