// farm-byte-portal/src/app/layout/navbar/navbar-profile/navbar-profile.component.ts
import {Component, HostListener, signal, WritableSignal} from '@angular/core';
import {TranslateModule} from "@ngx-translate/core";
import {NgClass} from "@angular/common";

@Component({
  selector: 'farmbyte-navbar-profile',
  standalone: true,
  imports: [
    TranslateModule,
    NgClass
  ],
  templateUrl: './navbar-profile.component.html',
  styleUrl: './navbar-profile.component.scss'
})
export class NavbarProfileComponent {

  isOpen: WritableSignal<boolean> = signal(false);

  toggleDropDown() {
    this.isOpen.set(!this.isOpen());
  }

  @HostListener('document:click', ['$event'])
  onClickOutside(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const clickInside = target.closest('#dropDownMenuItem_profile');
    if (!clickInside) {
      this.isOpen.set(false);
    }
  }
}

<a id="dropDownMenuItem_profile" (click)="toggleDropDown()" class="relative flex text-gray-500 py-1 px-2 cursor-pointer" >
  <div class="flex flex-row justify-center items-center gap-1">
    <span class="hover:text-orange-700">
      <img class="size-8 object-cover rounded-full" src="./images/profile.png" alt="profile">
    </span>
  </div>
  @if(isOpen()) {
    <div
      [ngClass]="isOpen()? 'transition ease-out duration-1000 transform opacity-100 scale-100' : 'transition ease-in duration-1000 transform opacity-0 scale-10'"
      class="absolute top-full right-0 mt-2 w-32 border-2 border-t-orange-700  bg-white shadow-lg z-10">

      <a class="block flex flex-row justify-start items-center text-sm p-2 gap-2 hover:transition hover:duration-300 hover:bg-gray-200 hover:text-black">
        <span>My Profile</span>
      </a>
      <a class="block flex flex-row justify-start items-center text-sm p-2 gap-2 hover:transition hover:duration-300 hover:bg-gray-300 hover:text-black">
        <span>Logout</span>
      </a>

    </div>
  }
</a>

// farm-byte-fronend/src/layouts/navbar/web-navbar/NavBarProfile.tsx
import React, {useEffect, useRef, useState} from "react";
import {useNavigate} from "react-router-dom";

const NavBarProfile = () => {

    const dropdownRef = useRef<HTMLDivElement>(null);
    const [isOpenProfileMenu, setIsOpenProfileMenu] = useState(false);

    const navigate = useNavigate();

    useEffect(() => {
        const closeDropDown = (event) => {
            if(dropdownRef.current && !dropdownRef.current.contains(event.target)) {
                setIsOpenProfileMenu(false);
            }
        }
        document.addEventListener("click", closeDropDown);
        return () => document.body.removeEventListener("click", closeDropDown);
    }, []);

    const toggleDropDown = () => {
        setIsOpenProfileMenu(!isOpenProfileMenu);
    }

    const handleNavigateTo = (event: React.MouseEvent<HTMLDivElement>, link: string) => {
        //TODO continue to find how to hide sub menu
        event.preventDefault();
        if(isOpenProfileMenu) {
            navigate(link);
        }
    }

    return (
        <div className="relative">
            <div
                ref={dropdownRef}
                onClick={toggleDropDown}
                className="flex flex-row justify-start items-center text-gray-500 hover:text-amber-700 cursor-pointer">
                <span className="font-medium">
                    <img src="/images/profile.png" alt="..." className="size-8 object-cover rounded-full"/>
                </span>

            </div>
            <div
                className={`absolute top-full -right-0 mt-[1.65rem] w-32 bg-white shadow-2xl z-10 rounded-b-lg ${isOpenProfileMenu ? 'transition duration-300 ease-in opacity-100 transform scale-110 cursor-pointer' : 'cursor-auto transition duration-300 ease-out opacity-0 scale-75'}`}>
                <div onClick={(event) => handleNavigateTo(event,'/user/profile')}
                      className="block text-gray-500 p-2 text-sm hover:text-white hover:bg-gradient-to-r hover:from-amber-800 hover:to-amber-400 hover:transition-all hover:ease-in-out hover:duration-300 ">My profile</div>
                <div onClick={(event) => handleNavigateTo(event, '/logout')}
                      className="block text-gray-500 p-2 text-sm hover:text-white  rounded-b-lg hover:bg-gradient-to-r hover:from-amber-800 hover:to-amber-400  hover:transition-all hover:ease-in-out hover:duration-300 ">Logout</div>
            </div>
        </div>
    );
}

export default NavBarProfile;
